export const CERTIFICATES_MAP = [
  { id: 1, src: "src/shared/assets/images/certificates/certificate1.jpg" },
  { id: 2, src: "src/shared/assets/images/certificates/certificate2.jpg" },
  { id: 3, src: "src/shared/assets/images/certificates/certificate3.jpg" },
  { id: 4, src: "src/shared/assets/images/certificates/certificate4.jpg" },
  { id: 5, src: "src/shared/assets/images/certificates/certificate5.jpg" },
  { id: 6, src: "src/shared/assets/images/certificates/certificate6.jpg" },
  { id: 7, src: "src/shared/assets/images/certificates/certificate7.jpg" },
  { id: 8, src: "src/shared/assets/images/certificates/certificate8.jpg" },
  { id: 9, src: "src/shared/assets/images/certificates/certificate9.jpg" },
  { id: 10, src: "src/shared/assets/images/certificates/certificate10.jpg" },
  { id: 11, src: "src/shared/assets/images/certificates/certificate11.jpg" },
  { id: 12, src: "src/shared/assets/images/certificates/certificate12.jpg" },
];

export const CLIENTS_MAP = [
  { id: 1, src: "src/shared/assets/images/clients/client1.png" },
  { id: 2, src: "src/shared/assets/images/clients/client2.png" },
  { id: 3, src: "src/shared/assets/images/clients/client3.png" },
  { id: 4, src: "src/shared/assets/images/clients/client4.png" },
  { id: 5, src: "src/shared/assets/images/clients/client5.png" },
  { id: 6, src: "src/shared/assets/images/clients/client6.png" },
  { id: 7, src: "src/shared/assets/images/clients/client7.png" },
  { id: 8, src: "src/shared/assets/images/clients/client8.png" },
  { id: 9, src: "src/shared/assets/images/clients/client9.png" },
  { id: 10, src: "src/shared/assets/images/clients/client10.png" },
  { id: 11, src: "src/shared/assets/images/clients/client11.png" },
  { id: 12, src: "src/shared/assets/images/clients/client12.png" },
  { id: 13, src: "src/shared/assets/images/clients/client13.png" },
  { id: 14, src: "src/shared/assets/images/clients/client14.png" },
  { id: 15, src: "src/shared/assets/images/clients/client15.png" },
  { id: 16, src: "src/shared/assets/images/clients/client16.png" },
  { id: 17, src: "src/shared/assets/images/clients/client17.png" },
  { id: 18, src: "src/shared/assets/images/clients/client18.png" },
];
